from __future__ import annotations

from typing import Any


def _lesson(
    title: str,
    level: str,
    focus: str,
    concept: str,
    examples: list[str],
    grammar_tip: str,
    vocabulary: list[str],
    learning_goals: list[str],
    practice_prompt: str,
    minutes: int,
) -> dict[str, Any]:
    return {
        "title": title,
        "level": level,
        "focus": focus,
        "concept": concept,
        "examples": examples,
        "grammar_tip": grammar_tip,
        "vocabulary": vocabulary,
        "learning_goals": learning_goals,
        "practice_prompt": practice_prompt,
        "minutes": minutes,
    }


LESSON_CONTENT: dict[str, list[dict[str, Any]]] = {
    "Spanish": [
        _lesson(
            "Greetings and Introductions",
            "Beginner",
            "Vocabulary",
            "Learn simple greetings, introductions, and polite expressions.",
            ["Hola - Hello", "Buenos dias - Good morning", "Me llamo Ana - My name is Ana", "Mucho gusto - Nice to meet you"],
            "Spanish greetings work across situations, but formal and informal choices matter.",
            ["hola", "buenos dias", "me llamo", "mucho gusto", "gracias"],
            ["Greet someone politely", "Say your name", "Respond to a first meeting"],
            "Introduce yourself in two short Spanish sentences.",
            8,
        ),
        _lesson(
            "Numbers and Everyday Objects",
            "Beginner",
            "Vocabulary",
            "Count to ten and name common objects around the house or classroom.",
            ["Uno, dos, tres - One, two, three", "La mesa - The table", "El libro - The book", "La puerta - The door"],
            "Articles change with noun gender, so memorize each noun with its article.",
            ["uno", "dos", "libro", "mesa", "puerta"],
            ["Count basic quantities", "Name classroom objects", "Notice article gender"],
            "Look around your room and name three objects in Spanish.",
            9,
        ),
        _lesson(
            "Present Tense Basics",
            "Beginner",
            "Grammar",
            "Build simple present tense sentences with regular verbs.",
            ["Yo estudio espanol - I study Spanish", "Tu hablas despacio - You speak slowly", "Nosotros vivimos aqui - We live here"],
            "Focus on verb endings because they carry subject information.",
            ["estudio", "hablas", "vivimos", "aprendo", "escucho"],
            ["Conjugate regular verbs", "Write subject + verb sentences", "Describe daily actions"],
            "Write one sentence about what you study and one about where you live.",
            10,
        ),
        _lesson(
            "Food and Ordering",
            "Beginner",
            "Conversation",
            "Use useful restaurant phrases and food vocabulary in simple exchanges.",
            ["Quiero una sopa - I want a soup", "La cuenta, por favor - The bill, please", "Tengo hambre - I am hungry", "Me gusta el cafe - I like coffee"],
            "Quiero is direct and useful; me gustaria sounds more polite in many contexts.",
            ["quiero", "agua", "cafe", "pan", "la cuenta"],
            ["Order politely", "Name common food items", "Express likes and needs"],
            "Pretend you are in a cafe and order a drink and a snack.",
            10,
        ),
        _lesson(
            "Asking for Directions",
            "Intermediate",
            "Conversation",
            "Ask where places are and understand simple directions in town.",
            ["Donde esta la estacion - Where is the station", "Siga recto - Go straight", "Gire a la izquierda - Turn left", "Esta cerca de aqui - It is near here"],
            "Question words like donde usually start the sentence without changing the rest much.",
            ["donde", "recto", "izquierda", "derecha", "cerca"],
            ["Ask location questions", "Follow short spoken directions", "Use place vocabulary"],
            "Ask how to get to the station, then answer your own question.",
            11,
        ),
        _lesson(
            "Past Experiences",
            "Intermediate",
            "Grammar",
            "Talk about what you did recently using common past-tense patterns.",
            ["Ayer visite a mi amiga - Yesterday I visited my friend", "Comimos temprano - We ate early", "Estudie por la noche - I studied at night", "Fue un buen dia - It was a good day"],
            "Time markers such as ayer make the tense easier to understand in context.",
            ["ayer", "visite", "comimos", "estudie", "fue"],
            ["Describe a past activity", "Recognize common preterite forms", "Use time expressions"],
            "Describe what you did yesterday in two short sentences.",
            12,
        ),
        _lesson(
            "Making Plans and Invitations",
            "Intermediate",
            "Conversation",
            "Invite someone somewhere, accept or decline politely, and suggest a time.",
            ["Quieres venir conmigo - Do you want to come with me", "Podemos vernos a las seis - We can meet at six", "Lo siento, no puedo - Sorry, I cannot", "Suena bien - That sounds good"],
            "Spanish often uses the present tense to talk about near-future plans in everyday conversation.",
            ["venir", "vernos", "a las seis", "no puedo", "suena bien"],
            ["Invite someone", "Set a meeting time", "Accept or decline politely"],
            "Invite a friend to meet for coffee tomorrow evening.",
            12,
        ),
        _lesson(
            "Expressing Opinions and Preferences",
            "Advanced",
            "Conversation",
            "Share opinions, compare options, and explain preferences with clearer detail.",
            ["Creo que es una buena idea - I think it is a good idea", "Prefiero esta opcion - I prefer this option", "En mi opinion, es mejor - In my opinion, it is better", "No estoy de acuerdo - I do not agree"],
            "Opinion phrases help you sound more natural and organized when speaking at length.",
            ["creo que", "prefiero", "en mi opinion", "mejor", "no estoy de acuerdo"],
            ["State opinions clearly", "Compare options", "Agree or disagree politely"],
            "Give your opinion about online learning in two or three Spanish sentences.",
            14,
        ),
    ],
    "French": [
        _lesson(
            "Bonjour Basics",
            "Beginner",
            "Vocabulary",
            "Start conversations with greetings and courtesy phrases.",
            ["Bonjour - Hello", "Bonsoir - Good evening", "Je m'appelle Louis - My name is Louis", "Merci beaucoup - Thank you very much"],
            "French pronunciation changes meaning, so repeat these aloud as you learn them.",
            ["bonjour", "bonsoir", "merci", "je m'appelle", "s'il vous plait"],
            ["Greet someone at different times", "Introduce yourself", "Say thank you and please"],
            "Write a short French greeting for meeting a teacher.",
            8,
        ),
        _lesson(
            "Family and Daily Life",
            "Beginner",
            "Vocabulary",
            "Learn words for family members and routine daily activities.",
            ["La mere - Mother", "Le pere - Father", "Je travaille aujourd'hui - I work today", "Nous mangeons ensemble - We eat together"],
            "French articles signal gender and number, so learn nouns with their article.",
            ["la mere", "le pere", "travaille", "mangeons", "famille"],
            ["Talk about family", "Describe a routine", "Use basic daily verbs"],
            "Describe one family member and one daily routine in French.",
            9,
        ),
        _lesson(
            "Simple Sentence Structure",
            "Beginner",
            "Grammar",
            "Form short subject-verb-object sentences in French.",
            ["Je lis un livre - I read a book", "Tu aimes la musique - You like music", "Ils parlent francais - They speak French"],
            "Keep agreement in mind even when the spoken form sounds similar.",
            ["lis", "aimes", "parlent", "livre", "musique"],
            ["Create full sentences", "Use present tense subjects", "Express simple preferences"],
            "Write one sentence about reading and one about music.",
            10,
        ),
        _lesson(
            "Shopping and Prices",
            "Beginner",
            "Conversation",
            "Ask how much things cost and make simple purchases.",
            ["Combien ca coute - How much does it cost", "Je prends celui-ci - I will take this one", "C'est trop cher - It is too expensive", "Je cherche une chemise - I am looking for a shirt"],
            "French often contracts naturally in speech, so listen for shortened sounds around vowels.",
            ["combien", "coute", "cher", "chemise", "prends"],
            ["Ask price questions", "React to cost", "State what you want to buy"],
            "Act out buying one item in a shop.",
            10,
        ),
        _lesson(
            "Time and Scheduling",
            "Intermediate",
            "Conversation",
            "Talk about time, appointments, and planning your day.",
            ["Il est huit heures - It is eight o'clock", "On se retrouve demain - We will meet tomorrow", "Je suis libre ce soir - I am free tonight", "A quelle heure - At what time"],
            "French uses fixed expressions for time, so memorize the core pattern first.",
            ["heure", "demain", "ce soir", "libre", "rendez-vous"],
            ["Tell the time", "Set up plans", "Ask when something happens"],
            "Invite a friend to meet tomorrow evening in French.",
            11,
        ),
        _lesson(
            "Describing the Past",
            "Intermediate",
            "Grammar",
            "Describe completed actions using common conversational past structures.",
            ["J'ai visite Paris - I visited Paris", "Nous avons regarde un film - We watched a movie", "Elle a etudie toute la nuit - She studied all night", "C'etait interessant - It was interesting"],
            "The passe compose needs an auxiliary verb plus the past participle.",
            ["j'ai", "avons", "regarde", "visite", "c'etait"],
            ["Recognize passe compose", "Talk about recent events", "Use opinion language about the past"],
            "Describe one enjoyable thing you did last weekend.",
            12,
        ),
        _lesson(
            "Invitations and Social Plans",
            "Intermediate",
            "Conversation",
            "Invite people, discuss plans, and respond to suggestions naturally.",
            ["Tu veux venir avec nous - Do you want to come with us", "On peut se retrouver demain - We can meet tomorrow", "Je suis disponible a sept heures - I am available at seven o'clock", "Bonne idee - Good idea"],
            "French often uses simple present forms for planned future events in everyday speech.",
            ["venir", "demain", "disponible", "bonne idee", "se retrouver"],
            ["Invite someone", "Propose a time", "React naturally to a suggestion"],
            "Invite a friend to meet tomorrow and suggest a time.",
            12,
        ),
        _lesson(
            "Opinions, Comparisons, and Debate",
            "Advanced",
            "Conversation",
            "Express preferences, compare choices, and support your opinion politely.",
            ["Je pense que c'est utile - I think that it is useful", "Je prefere cette option - I prefer this option", "A mon avis, c'est plus pratique - In my opinion, it is more practical", "Je ne suis pas d'accord - I do not agree"],
            "Opinion markers like a mon avis make your speech more structured and fluent.",
            ["je pense que", "je prefere", "a mon avis", "plus pratique", "pas d'accord"],
            ["Share an opinion", "Compare two options", "Agree or disagree politely"],
            "Write two French sentences comparing classroom learning and online learning.",
            14,
        ),
    ],
    "German": [
        _lesson(
            "Everyday Greetings",
            "Beginner",
            "Vocabulary",
            "Use basic greetings, introductions, and polite phrases in German.",
            ["Hallo - Hello", "Guten Morgen - Good morning", "Ich heisse Max - My name is Max", "Freut mich - Nice to meet you"],
            "German nouns are capitalized, but greetings and names also depend on formality.",
            ["hallo", "guten Morgen", "ich heisse", "freut mich", "danke"],
            ["Say hello appropriately", "Introduce yourself", "Respond politely in a first meeting"],
            "Write a short self-introduction in German.",
            8,
        ),
        _lesson(
            "Home and School Words",
            "Beginner",
            "Vocabulary",
            "Learn useful nouns for home, school, and study.",
            ["Das Buch - The book", "Der Tisch - The table", "Die Schule - The school", "Das Fenster - The window"],
            "Always pair German nouns with der, die, or das when studying vocabulary.",
            ["das Buch", "der Tisch", "die Schule", "das Fenster", "der Stuhl"],
            ["Name common objects", "Associate nouns with articles", "Build noun recall"],
            "Name five things you can see in a room in German.",
            9,
        ),
        _lesson(
            "Verb Position Fundamentals",
            "Beginner",
            "Grammar",
            "Understand basic German sentence structure with the verb in second position.",
            ["Ich lerne Deutsch - I learn German", "Wir spielen heute - We play today", "Er trinkt Wasser - He drinks water"],
            "In main clauses, the conjugated verb usually comes second even when another element starts the sentence.",
            ["lerne", "spielen", "trinkt", "heute", "Deutsch"],
            ["Build basic statements", "Notice second-position verbs", "Add time words correctly"],
            "Write two German sentences that include a time word like heute.",
            10,
        ),
        _lesson(
            "Travel and Transport",
            "Beginner",
            "Conversation",
            "Buy tickets, ask about transport, and understand simple travel questions.",
            ["Wo ist der Bahnhof - Where is the train station", "Eine Fahrkarte, bitte - One ticket, please", "Wann faehrt der Zug - When does the train leave", "Ich moechte nach Berlin - I would like to go to Berlin"],
            "Modal-like phrases such as ich moechte make requests sound natural and polite.",
            ["Bahnhof", "Fahrkarte", "Zug", "faehrt", "moechte"],
            ["Ask for a ticket", "Talk about destinations", "Understand travel timing"],
            "Pretend you need a train ticket to Berlin.",
            10,
        ),
        _lesson(
            "Daily Routine in Detail",
            "Intermediate",
            "Conversation",
            "Describe what you do during the day with connected sentences.",
            ["Ich stehe um sieben Uhr auf - I get up at seven o'clock", "Dann fruehstuecke ich - Then I eat breakfast", "Am Abend lerne ich - In the evening I study", "Spaeter gehe ich schlafen - Later I go to sleep"],
            "Separable verbs like aufstehen split in present tense main clauses.",
            ["aufstehen", "fruehstuecken", "am Abend", "spaeter", "schlafen"],
            ["Describe a routine step by step", "Use sequence words", "Recognize separable verbs"],
            "Describe your morning routine in three German sentences.",
            11,
        ),
        _lesson(
            "Speaking About Yesterday",
            "Intermediate",
            "Grammar",
            "Use conversational past forms to describe what happened yesterday.",
            ["Ich habe gearbeitet - I worked", "Wir haben Fussball gespielt - We played football", "Sie hat Musik gehoert - She listened to music", "Gestern war ich muede - Yesterday I was tired"],
            "German spoken past often uses haben plus a past participle.",
            ["gestern", "habe", "gespielt", "gehoert", "muede"],
            ["Talk about past events", "Use gestern for context", "Recognize perfect tense patterns"],
            "Write two things you did yesterday in German.",
            12,
        ),
        _lesson(
            "Making Plans Together",
            "Intermediate",
            "Conversation",
            "Invite someone out, talk about availability, and suggest a meeting time.",
            ["Hast du morgen Zeit - Do you have time tomorrow", "Wir koennen uns um sechs treffen - We can meet at six", "Das klingt gut - That sounds good", "Leider kann ich nicht - Unfortunately I cannot"],
            "German often keeps time expressions close to the middle of the sentence while preserving verb position.",
            ["Zeit", "morgen", "treffen", "klingt gut", "leider"],
            ["Invite someone", "Talk about availability", "Agree or decline politely"],
            "Invite a friend to meet tomorrow at six in German.",
            12,
        ),
        _lesson(
            "Sharing Opinions Clearly",
            "Advanced",
            "Conversation",
            "Express opinions, compare ideas, and respond thoughtfully in German.",
            ["Ich denke, dass es wichtig ist - I think that it is important", "Ich bevorzuge diese Option - I prefer this option", "Meiner Meinung nach ist es besser - In my opinion it is better", "Ich bin nicht ganz einverstanden - I do not fully agree"],
            "Structures with dass help you connect an opinion to a supporting statement.",
            ["ich denke", "bevorzuge", "meiner Meinung nach", "besser", "einverstanden"],
            ["State and support an opinion", "Compare alternatives", "Disagree politely"],
            "Write your opinion about learning languages with technology in German.",
            14,
        ),
    ],
    "Hindi": [
        _lesson(
            "Namaste and Introductions",
            "Beginner",
            "Vocabulary",
            "Practice basic Hindi greetings and self-introductions.",
            ["Namaste - Hello", "Aap kaise hain - How are you", "Mera naam Riya hai - My name is Riya", "Dhanyavaad - Thank you"],
            "Hindi often changes tone based on respect level, especially with pronouns like aap and tum.",
            ["namaste", "aap", "mera naam", "dhanyavaad", "kaise hain"],
            ["Greet respectfully", "Say your name", "Ask how someone is"],
            "Introduce yourself politely in Hindi.",
            8,
        ),
        _lesson(
            "Family and Common Nouns",
            "Beginner",
            "Vocabulary",
            "Learn common household nouns and words for family members.",
            ["Ghar - House", "Paani - Water", "Maa - Mother", "Dost - Friend"],
            "Hindi nouns can be masculine or feminine and affect the sentence around them.",
            ["ghar", "paani", "maa", "dost", "pitaji"],
            ["Name common people and objects", "Grow basic noun vocabulary", "Notice noun gender"],
            "Name your home, one family member, and one friend in Hindi.",
            9,
        ),
        _lesson(
            "Simple Present Sentences",
            "Beginner",
            "Grammar",
            "Build short present tense sentences for everyday activities.",
            ["Main padhta hoon - I study", "Woh gaana gaati hai - She sings", "Hum khelte hain - We play"],
            "Verb forms often change based on gender and number, so examples matter.",
            ["padhta", "gaati", "khelte", "hai", "hain"],
            ["Describe routine actions", "Match verbs to subjects", "Recognize basic present endings"],
            "Write one sentence about studying and one about playing in Hindi.",
            10,
        ),
        _lesson(
            "Food, Home, and Needs",
            "Beginner",
            "Conversation",
            "Use simple Hindi to ask for food, water, and help at home.",
            ["Mujhe paani chahiye - I need water", "Khaana bahut accha hai - The food is very good", "Mujhe madad chahiye - I need help", "Roti kahan hai - Where is the bread"],
            "Chahiye is extremely useful for expressing needs and wants politely.",
            ["chahiye", "khaana", "paani", "madad", "kahan"],
            ["Express needs", "Talk about food", "Ask where something is"],
            "Say what you need and what food you like in Hindi.",
            10,
        ),
        _lesson(
            "Directions and Places",
            "Intermediate",
            "Conversation",
            "Ask where places are and understand simple local directions.",
            ["Station kahan hai - Where is the station", "Seedha jaiye - Go straight", "Daayen mudiyega - Turn right", "Yeh paas mein hai - It is nearby"],
            "Hindi often uses polite verb forms such as jaiye in public situations.",
            ["station", "seedha", "daayen", "paas", "kahan"],
            ["Ask for directions", "Understand route language", "Use polite public phrases"],
            "Ask for the station and give one direction in Hindi.",
            11,
        ),
        _lesson(
            "Talking About Yesterday",
            "Intermediate",
            "Grammar",
            "Describe recent actions and routines from the previous day.",
            ["Kal main bazaar gaya tha - Yesterday I went to the market", "Humne film dekhi - We watched a movie", "Usne kaam kiya - He did work", "Kal din accha tha - Yesterday was a good day"],
            "Past forms in Hindi shift with gender and sentence structure, so model examples are important.",
            ["kal", "gaya tha", "dekhi", "kiya", "accha tha"],
            ["Talk about the past", "Use time markers", "Recognize common past constructions"],
            "Describe one thing you did yesterday in Hindi.",
            12,
        ),
        _lesson(
            "Making Friendly Plans",
            "Intermediate",
            "Conversation",
            "Invite someone, suggest a time, and respond to a plan naturally.",
            ["Kya tum kal aa sakte ho - Can you come tomorrow", "Hum shaam ko mil sakte hain - We can meet in the evening", "Theek hai, main aaunga - Okay, I will come", "Maaf kijiye, main vyast hoon - Sorry, I am busy"],
            "Hindi often uses context and polite forms to make invitations sound warm rather than direct.",
            ["kal", "mil sakte hain", "shaam", "aaunga", "vyast"],
            ["Invite someone", "Suggest a time", "Accept or decline politely"],
            "Invite a friend to meet tomorrow evening in Hindi.",
            12,
        ),
        _lesson(
            "Opinions and Preferences",
            "Advanced",
            "Conversation",
            "Explain what you prefer, share opinions, and compare ideas in Hindi.",
            ["Mujhe lagta hai ki yeh accha hai - I think this is good", "Mujhe yeh zyada pasand hai - I like this more", "Meri rai mein yeh behtar hai - In my opinion this is better", "Main sehmat nahin hoon - I do not agree"],
            "Opinion phrases make spoken Hindi more expressive and help learners move beyond one-word answers.",
            ["mujhe lagta hai", "pasand", "meri rai mein", "behtar", "sehmat"],
            ["Share opinions clearly", "Express a preference", "Agree or disagree respectfully"],
            "Give your opinion about studying in the morning versus at night in Hindi.",
            14,
        ),
    ],
}


LEVEL_ORDER = {"Beginner": 1, "Intermediate": 2, "Advanced": 3}


def get_languages() -> list[str]:
    return list(LESSON_CONTENT.keys())


def get_lessons(language: str) -> list[dict[str, Any]]:
    return LESSON_CONTENT.get(language, [])


def get_lesson(language: str, lesson_title: str) -> dict[str, Any] | None:
    return next((lesson for lesson in get_lessons(language) if lesson["title"] == lesson_title), None)


def get_lesson_catalog_summary(language: str) -> dict[str, Any]:
    lessons = get_lessons(language)
    by_level: dict[str, int] = {}
    by_focus: dict[str, int] = {}

    for lesson in lessons:
        by_level[lesson["level"]] = by_level.get(lesson["level"], 0) + 1
        by_focus[lesson["focus"]] = by_focus.get(lesson["focus"], 0) + 1

    return {
        "count": len(lessons),
        "levels": by_level,
        "focus_areas": by_focus,
        "minutes": sum(lesson["minutes"] for lesson in lessons),
    }


def get_recommended_next_step(language: str, completed_lessons: set[str]) -> str:
    for lesson in get_lessons(language):
        if lesson["title"] not in completed_lessons:
            return f"Next best step: complete '{lesson['title']}' in {language}."
    return f"You have completed all current {language} lessons. Use the AI Tutor to deepen fluency."
